[#7] [Chore] [Android] Configure CD for the project
nimblehq/ic-kmm-kayla-bruce pull request #86
Opened 2023-08-18 11:29 UTC by thiennguyen0196

- Close #7 

## What happened 👀

Provide a description of the **changes** this pull request brings to the codebase. Additionally, when the pull request is still being worked on, a checklist of the planned changes is welcome to track progress.

## Insight 📝

Describe in detail why this solution is the most appropriate, which solution you tried but did not go with, and how to test the changes. References to relevant documentation are welcome as well.

## Proof Of Work 📹

Show us the implementation: screenshots, GIFs, etc.

<img src="URL_GOES_HERE" width=200 />

2023-08-23 08:12 UTC, nmint8m requested changes

2023-08-23 08:12 UTC, nmint8m commented on .github/workflows/android_shared_lint_and_test.yml
> +          echo $GOOGLE_SERVICES_JSON_STAGING > android/src/staging/google-services.json
Please check my suggestion to see if it works (to make it consistent with build konfig)
```suggestion
          echo "$GOOGLE_SERVICES_JSON_STAGING" > android/src/staging/google-services.json
```

2023-08-23 08:12 UTC, nmint8m commented on signing.properties
> +KEY_ALIAS=
I would prefer to have an example file instead `signing.properties.example`, then put this file into `.gitignore`

2023-08-23 12:03 UTC, thiennguyen0196 commented
I have tested and resolved your concerns in this commit https://github.com/nimblehq/ic-kmm-kayla-bruce/pull/86/commits/da2faafabdc7e0158ecf9d80a1685d4c174d3728 @nmint8m 
Please check it again. Many thanks 👏 

<img width="700" alt="Screenshot 2023-08-23 at 7 00 55 PM" src="https://github.com/nimblehq/ic-kmm-kayla-bruce/assets/25218255/3485a2fc-33bc-4b64-8c1b-d871da40caa0">

2023-08-24 02:39 UTC, nmint8m approved these changes
Look good to me now

2023-08-24 02:47 UTC, markgravity approved these changes

2023-08-24 07:26 UTC, merged