[#23] [UI] [iOS] As a user, I can see the animation when loading and showing surveys
nimblehq/ic-kmm-kayla-bruce pull request #88
Opened 2023-08-22 08:26 UTC by nmint8m

- Close #23

## What happened 👀

In this PR, I show the animation when loading and showing surveys.

## Insight 📝

N/A

## Proof Of Work 📹

<img src="[URL_GOES_HERE](https://github.com/nimblehq/ic-kmm-kayla-bruce/assets/23162627/b9a65cd9-2c3e-42c3-aeaa-65696312bc7e)" width=200 />

2023-08-23 03:50 UTC, markgravity commented
@nmint8m I cant see your POW 🙏

2023-08-23 05:07 UTC, thiennguyen0196 reviewed
I cannot see your POW too @nmint8m 
And please also rebase your branch, currently it has conflicts 🙏

2023-08-24 03:38 UTC, thiennguyen0196 requested changes
@nmint8m The code style is good to me 👏 However for the UI, I see differences between Figma and your POW 🤔 I think it has these issues:
1. The home header skeleton section should have the longer part on top of the short one, and two lines of skeleton should have the same height
2. The survey list skeleton is missing a small skeleton text/box on top 
3. The color of skeleton should have higher opacity value, maybe 0.7 and 0.3 would be more accurate 🤔 

| Figma | POW |
|-|-|
| <img width="200" alt="Screenshot 2023-08-24 at 10 29 46 AM" src="https://github.com/nimblehq/ic-kmm-kayla-bruce/assets/25218255/7cc62add-694a-4b2d-9a60-e573bea9f58b"> | <img width="200" alt="Screenshot 2023-08-24 at 10 30 26 AM" src="https://github.com/nimblehq/ic-kmm-kayla-bruce/assets/25218255/3d5f36b6-fac6-4b11-b415-e9ce50e72797"> |


|

2023-08-24 07:34 UTC, nmint8m commented
@thiennguyen0196 I updated the POW

2023-08-24 09:41 UTC, markgravity commented on ios/ios/Sources/Presentation/Modules/Home/SurveyList/SurveyListSkeletonView.swift
> +                    width: geometry.size.width - 50,
Missing zero here `50.0` 🙏

2023-08-25 04:22 UTC, thiennguyen0196 approved these changes
Apart from @markgravity 's comments, the rest LGTM

2023-08-25 08:16 UTC, nmint8m commented
@markgravity Please help me review this PR. Thank you.

2023-08-28 03:06 UTC, markgravity approved these changes

2023-08-28 03:27 UTC, merged